### PR TITLE
Fix weird autocmd group names

### PR DESCRIPTION
**Pull request by obcat**
Problem : augroup "0", "1", and "2" are registered.
Solution: Use proper operator for string concatenation.

### CODE REVIEW

**Comment by mattn** [comment]
You should send this pull-request to https://github.com/prabirshrestha/callbag.vim/blob/e5f02bd3beb57b335bc8fcdfbec91458c5928c8a/autoload/callbag.vim#L467

Thanks

**Comment by obcat** [comment]
Oh, I see. I'll do it.

**Comment by obcat** [comment]
Done.

**Comment by mattn** [comment]
Please keep this open until that https://github.com/prabirshrestha/callbag.vim/pull/25 will be merged and including it to vim-lsp.

**Comment by prabirshrestha** [comment]
I have merged the callbag.vim PR.

Please use the following line to update callbag.vim in vim-lsp

https://github.com/prabirshrestha/vim-lsp/blob/ed4d1e9da1b2ede4e729b21ec72d3ece2cb76102/autoload/lsp/callbag.vim#L2

**Comment by obcat** [comment]
Updated.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Comment by obcat** [comment]
Thanks too!

**Comment by prabirshrestha** [comment]
Out of curiosity how did you find the bug?

**Comment by obcat** [comment]
I found that augroups when typing `:aug <Tab>`. They were at the top of wildmenu in my environment.

**Pull request merged**
