### PR TITLE
Add diagnostics highlighting via +textprop.

### PR DESCRIPTION
**Pull request by tsufeki**
Add diagnostics highlights using text properties introduced in vim patch 8.1.0579

Turned off by default as text properties are not stable yet.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Could you provide screenshots and gifs?

**Comment by tsufeki** [comment]
image

**Comment by prabirshrestha** [comment]
Looks good to me. Can we enable this by default and add docs?

**Comment by tsufeki** [comment]
Done. I also added docs for `g:lsp_highlights_enabled`.

Text props don't seem to be stable yet though (I occasionally get an "internal error" when editing). Should we assume users know what they're doing by using development version of vim?

**Comment by prabirshrestha** [comment]
If it isn’t stable ok to not enable it by default.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

Once text prop gets stable we most likely can remove that flag and just use highlights flag.

**Pull request merged**
