### PR TITLE
Allow specifying max width for floating windows

### PR DESCRIPTION
**Pull request by yuilib**
The max width for floating windows are `&columns * 0.4` and not configurable.
This PR gives an option to specify the max width for floating windows not only as `&columns * 0.4` but also as `&columns` or a specific positive number.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Can we use `g:lsp_float_max_width` and also update the docs instead?

**Comment by yuilib** [comment]
@prabirshrestha Done.

**Comment by prabirshrestha** [comment]
looks good. @yuilib can you fix the merge conflicts.

**Comment by yuilib** [comment]
@prabirshrestha The conflicts are resolved!

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
