### PR TITLE
Fix #516

### LINKED ISSUE #516: :LspDocumentFormat doesn't change anything despite the language server returning the formatted text
windows 10
gvim 8.1
When I want to format a file containing `Var    x;` (with extra spaces in between) and use `:LspDocumentFormat`, vim just switches to the visual mode without changing anything. The logs show that the language server returns the formatted text:

```
19.09.2019 11:16:56:["--->",1,"bsl-language-server",{"method":"textDocument/didOpen","params":{"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl","version":1,"languageId":"bsl","text":"Var   x;\n\n"}}}]
...
19.09.2019 11:17:06:["--->",1,"bsl-language-server",{"method":"textDocument/formatting","on_notification":"---funcref---","sync":0,"params":{"options":{"insertSpaces":false,"tabSize":8},"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl"}}}]
19.09.2019 11:17:06:["<---",1,"bsl-language-server",{"response":{"id":3,"jsonrpc":"2.0","result":[{"range":{"end":{"character":1,"line":1},"start":{"character":0,"line":0}},"newText":"Var x;\n"}]},"request":{"id":3,"jsonrpc":"2.0","method":"textDocument/formatting","params":{"options":{"insertSpaces":false,"tabSize":8},"textDocument":{"uri":"file:///C:/Users/xxx/Documents/2.bsl"}}}}]
19.09.2019 11:17:06:["s:build_cmd","keepjumps keepalt b 1 | execute 'keepjumps normal! 1G0v2G01l\"=l:merged_text_edit[''merged''][''newText''].''?''\rgph\"_x'"]
```

### PR DESCRIPTION
**Pull request by mattn**

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, test is failing

**Comment by clason** [comment]
This commit broke `LspDocumentFormat` from `texlab`: A spurious closing character is added.

Here's a minimal example: Before
```bibtex
@article{article,                                                                          
  author  = {Peter Adams}, 
  title   = {The title of the work},
  journal = {The name of the journal},
  year    = 1993,
  number  = 2,
  pages   = {201-213},
  month   = 7,
  note    = {An optional note}, 
  volume  = 4
}
```
After:
```bibtex
@article{article,                                                                          
    author = {Peter Adams},
    title = {The title of the work},
    journal = {The name of the journal},
    year = 1993, 
    number = 2,
    pages = {201-213},
    month = 7,
    note = {An optional note},  
    volume = 4,
}}
```
(note the -- incorrect -- last line).

Here's the corresponding vim-lsp log with the bad commit
```
Mon 23 Sep 2019 11:51:29 AM CEST:["--->", 8, "texlab", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize": 4}, "textDocument": {"uri": "file:///home/clason/test.   bib"}}}]
Mon 23 Sep 2019 11:51:29 AM CEST:["<---", 8, {"method": "workspace/configuration", "jsonrpc": "2.0", "id": 0, "params": {"items": [{"section": "bibtex.formatting"}]}}]       
Mon 23 Sep 2019 11:51:29 AM CEST:["--->", 8, "texlab", {"id": 0, "result": [null]}]        
Mon 23 Sep 2019 11:51:29 AM CEST:["<---", 8, "texlab", {"response": {"id": 3, "jsonrpc":   "2.0", "result": [{"range": {"end": {"character": 1, "line": 10}, "start": {"character":   0, "line": 0}}, "newText": "@article{article,\n    author = {Peter Adams},\n    title =    {The title of the work},\n    journal = {The name of the journal},\n    year = 1993,\n     number = 2,\n    pages = {201-213},\n    month = 7,\n    note = {An optional note},\n      volume = 4,\n}"}]}, "request": {"id": 3, "jsonrpc": "2.0", "method": "textDocument/        formatting", "params": {"options": {"insertSpaces": true, "tabSize": 4}, "textDocument":   {"uri": "file:///home/clason/test.bib"}}}}]                                                
Mon 23 Sep 2019 11:51:29 AM CEST:["s:build_cmd", "keepjumps keepalt b 1 | execute          'keepjumps normal! 1G0v11G0\"=l:merged_text_edit[''merged''][''newText''].''?''\rgph\"_x'"]
```
And here's the log without this commit:
```
Mon 23 Sep 2019 12:08:23 PM CEST:["--->", 8, "texlab", {"method": "textDocument/formatting", "on_notification": "---funcref---", "sync": 0, "params": {"options": {"insertSpaces": true, "tabSize": 4}, "textDocument": {"uri": "file:///home/clason/test.bib"}}}]
Mon 23 Sep 2019 12:08:23 PM CEST:["<---", 8, {"method": "workspace/configuration", "jsonrpc": "2.0", "id": 0, "params": {"items": [{"section": "bibtex.formatting"}]}}]
Mon 23 Sep 2019 12:08:23 PM CEST:["--->", 8, "texlab", {"id": 0, "result": [null]}]
Mon 23 Sep 2019 12:08:23 PM CEST:["<---", 8, "texlab", {"response": {"id": 3, "jsonrpc": "2.0", "result": [{"range": {"end": {"character": 1, "line": 10}, "start": {"character": 0, "line": 0}}, "newText": "@article{article,\n    author = {Peter Adams},\n    title = {The title of the work},\n    journal = {The name of the journal},\n    year = 1993,\n    number = 2,\n    pages = {201-213},\n    month = 7,\n    note = {An optional note},\n    volume = 4,\n}"}]}, "request": {"id": 3, "jsonrpc": "2.0", "method": "textDocument/formatting", "params": {"options": {"insertSpaces": true, "tabSize": 4}, "textDocument": {"uri": "file:///home/clason/test.bib"}}}}]
Mon 23 Sep 2019 12:08:23 PM CEST:["s:build_cmd", "keepjumps keepalt b 1 | execute 'keepjumps normal! 1G0v11G01l\"=l:merged_text_edit[''merged''][''newText''].''?''\rgph\"_x'"]
```

**Comment by mattn** [comment]
Will look into it in later

**Comment by mattn** [comment]
Sorry, This is broken. For https://github.com/prabirshrestha/vim-lsp/issues/516, it had to fix with going cursor up previous line.

**Comment by mattn** [comment]
I confirmed @clason 's log but can't reproduce. Hmm.

**Pull request merged**
