### PR TITLE
Handle disabled code action

### PR DESCRIPTION
**Pull request by rhysd**
[LSP v3.16](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#textDocument_codeAction) defines `disabled` optional property to response of CodeAction request.

```
	/**
	 * Marks that the code action cannot currently be applied.
	 *
	 * Clients should follow the following guidelines regarding disabled code
	 * actions:
	 *
	 * - Disabled code actions are not shown in automatic lightbulbs code
	 *   action menus.
	 *
	 * - Disabled actions are shown as faded out in the code action menu when
	 *   the user request a more specific type of code action, such as
	 *   refactorings.
	 *
	 * - If the user has a keybinding that auto applies a code action and only
	 *   a disabled code actions are returned, the client should show the user
	 *   an error message with `reason` in the editor.
	 *
	 * @since 3.16.0
	 */
	disabled?: {

		/**
		 * Human readable description of why the code action is currently
		 * disabled.
		 *
		 * This is displayed in the code actions UI.
		 */
		reason: string;
	};
```

This PR shows the reason of the disabled action and stops the command execution.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank you for your contribution.

I think we should add `disabledSupport = true` for the ClientCapabilities.

**Comment by rhysd** [comment]
Thank you for the point. I'll update the code.

**Comment by rhysd** [comment]
I added `disabledSupport` capability to supported capabilities at b8d2a7d

**Comment by hrsh7th** [comment]
LGTM!

**Review by hrsh7th — APPROVED** [review]

**Comment by hrsh7th** [comment]
The code-action signs can be improved but it can be another PR, I think.

**Pull request merged**
