### PR TITLE
[WIP] Improve signature help

### PR DESCRIPTION
**Pull request by hrsh7th**
I improved signature help behavior.

This PR aims to solve #493.

vim
vim-sig

nvim
nvim-sig

Another topic, I think nvim's float-window positioning can be improvements.

vim's popup-window is above of cursorline, it's nice.
But nvim's is not, So often signature-help overlap to pum.

### CODE REVIEW

**Comment by hrsh7th** [comment]
Thank @williamboman! Your feedback is very helpful for me.

> I've also had issues with the preview window staying while leaving insert mode, and the only way to get it to disappear is to re-create the buffer or :pclose. This happens quite often, and I've not been able to figure out why just yet.

Hm... I don't met the problem but it can be solve (for example, add `CursorMoved` to `s:add_closing_hooks`.

> The main pain point for me is the lack of ability to disable the automatic preview window when I don't want it. It's very eager to display itself whenever in insert mode.
Sorry, it is not understood me now.
If you can explain the problem, I try to solve it.

**Comment by hrsh7th** [comment]
At the moment, This PR to be WIP.

**Comment by prabirshrestha** [comment]
@hrsh7th any update on this? This does seem to fix the issue when install lexima.vim it used to always remove the signature.

**Comment by hrsh7th** [comment]
Currently, the PR works well but bit noisy behavior.
I have no idea to improve the behavior.
Yes, I think the PR fixes problem that related lexima.vim.

1. Close this PR.
2. Open new small PR that has only fixed lexima.vim related problems.

I will try it.

My currently aiming other things

- Fixing behavior at `CompleteDone`
- Refactor text_edit to use functions instead of commands

**Comment by hrsh7th** [comment]
I've supported lexima.vim in #638.
This PR's UI is not better for everyone.
So I close this for now.

**Pull request closed without merging**
