### PR TITLE
Signature help

### PR DESCRIPTION
**Pull request by mattn**
terminal7

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Does it work for plugins that autoclose the brackets such as https://github.com/cohama/lexima.vim?

**Comment by mattn** [comment]
I don't make sure but I won't work. So i add `g:lsp_signature_help_enabled`. The users of lexima should call `lsp#capabilities#get_signature_help_trigger_characters` them-self.

**Comment by mattn** [comment]
Anyway i'll check with lexima.

**Comment by mattn** [comment]
I checked this PR with lexima. As I mentioned above, lexima is diabled. So user should add custom rule of lexima.

**Comment by prabirshrestha** [comment]
We should add comment in the doc so it will allow people to troubleshoot on their own.

**Comment by mattn** [comment]
And default is off?

**Comment by prabirshrestha** [comment]
Can on it by default.

**Comment by mattn** [comment]
I notice that I can use InsertCharPre to do. Now we can use this with lexima.

**Comment by mattn** [comment]
I'm okay to merge.

**Comment by prabirshrestha** [comment]
Look good to me. 
It didn't work with lexima for me. Haven't dug deep into why.

**Pull request merged**
