### PR TITLE
Added g:lsp_signs_priority

### PR DESCRIPTION
**Pull request by smhc**
Allows configuring the priority of placed signs - useful when used along-side "signify" and other plugins that make use of the sign column.

### CODE REVIEW

**Comment by smhc** [comment]
In retrospect we may wish to assign different priorities to different severity levels (warning vs error)

**Comment by mattn** [comment]
Sorry my delay. Could you please fix conflict?

**Comment by clason** [comment]
@mattn This PR is rebased on top of PR #470 and add further functionality -- can it be merged as well?

**Comment by mattn** [comment]
LGTM

**Comment by mattn** [comment]
Thank you

**Comment by thomasfaingnaert** [comment]
@mattn I noticed you merge PRs using a merge commit, while @prabirshrestha squashes.
Can each collaborator choose his merge strategy, or are there some guidelines to follow?
Personally, I always squash so the `master` git log remains clean.

**Comment by prabirshrestha** [comment]
I prefer squash as it keeps the history clean.

**Comment by thomasfaingnaert** [comment]
@prabirshrestha Would it make sense to disable the other merge options?

**Comment by mattn** [comment]
Sorry, I will carefull in next time.

**Pull request merged**
