### PR TITLE
Highlight priority

### PR DESCRIPTION
**Pull request by mattn**
before
image

after
image

### CODE REVIEW

**Comment by mattn** [comment]
Sorry, will fix commiets.

**Comment by mattn** [comment]
Please wait merge.

**Comment by mattn** [comment]
@prabirshrestha Could you please review this order?

https://github.com/prabirshrestha/vim-lsp/pull/1298/files#diff-8cfa1d37b8a74ade416d2ccee240ddc6038a3d73bc3d8a6ef87dd8fda701c27cR1

**Review by prabirshrestha — APPROVED** [review]
LGTM

**Comment by mattn** [comment]
Thank you

**Pull request merged**
