### PR TITLE
refactor LspHover

### PR DESCRIPTION
**Pull request by prabirshrestha**
- [x] use callbag
- [ ] use new floating window api with markup content
- [ ] add support for using preview window instead of floating window - https://github.com/prabirshrestha/vim-lsp/issues/1047
- [ ] verify bug no longer exists https://github.com/prabirshrestha/vim-lsp/issues/1045 
- [ ] verify scroll works - https://github.com/prabirshrestha/vim-lsp/pull/1058
- [ ] verify complete doc floating window closes when using hover and vice versa
- [ ] verify diagnostics floating window closes when using hover and vice versa. (might need to port diagnostics to floating window api first)
- [ ] double tap support i.e. focus on neovim.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@hrsh7th can you have a look at this PR and help convert to the new floating api. We might want to getting the scroll api first. 

Few questions.
1. should we have a high level popup manager api. feel free to propose or send PRs on how you were thinking about it. 
2. similar to floating window api, should we have a preview window api in vim-vital-vs?

**Comment by hrsh7th** [comment]
I was considered adding `preview-window` support in vim-vital-vs but I gave up it.
I didn't found the correct abstraction for it...

Hm... I think if we vim-lsp should support `preview-window` as a fallback, we should create `lsp#internal#ui#preview` utility (it only focussing to handle preview window, not a floating window).

**Comment by hrsh7th** [comment]
Currently, `VS.Vim.Window.FloatingWindow` has the following APIs.

```
new
get_size
set_bufnr
get_bufnr
get_winid
info
set_var
get_var
open
close
enter
is_visible
```

I think it's difficult to support the same APIs in `VS.Vim.Window.SplitedWindow`.
I think `get_size`/`info`/open` will be a different signature.

If you can allow these differences, I can create `SplitedWindow` module.

**Comment by prabirshrestha** [comment]
I don't think preview and hover can be same api. It should be different.

We can create `SplitWindow` module. We should have an option to stack at a particular position such as top or bottom.

For now I have been converting everything to callbag api so it becomes easy to refactor.

Now that scroll PR is checked in this should be good to merge and we can move to the new popup api after it.

**Comment by prabirshrestha** [comment]
@hrsh7th Feel free to convert the hover to use the new popup api.

I will work on converting other apis to callbag.

**Comment by hrsh7th** [comment]
OK. I will create `SplitWindow` module (I don't know which is the better name `SplitedWindow` or `SplitWindow`).

**Comment by rafi** [comment]
This revision stopped hover documentation working for a file with multiple servers, e.g. html & tailwindcss. Previously I could see tailwindcss hover information, now it seems only the first server is queried.

**Pull request merged**
