### PR TITLE
added lsp#utils#location#_lsp_to_vim_list

### PR DESCRIPTION
**Pull request by prabirshrestha**
- [x] add `lsp#utils#location#_lsp_to_vim_list`
- [x] remove `lsp#ui#vim#utils#locations_to_loc_list()`
- [ ] add tests

### CODE REVIEW

**Comment by clason** [comment]
Commit https://github.com/prabirshrestha/vim-lsp/commit/b02345d2231e16d92b8b153fe6f1f0867e0b3b56 broke `PeekDefinition` for me -- the range from the `LocationLink` are now off by one (i.e., shifted down). I don't see anything obvious in that commit that should cause this, though.

**Comment by prabirshrestha** [comment]
```
let [l:line, l:col] = lsp#utils#position#_lsp_to_vim(l:path, l:range['start'])

    let l:index = l:line - 1
```

Can you try removing -1 or any of those +1 -1 since, `_lsp_to_vim` already should be doing that correctly.

**Comment by clason** [comment]
Yes, just noticed that bit myself. Changing the `-1` in location.vim doesn't help, but removing the `+1` in position.vim does. The latter breaks `References`, though.

**Comment by clason** [comment]
I don't think the preview lines from locationlink should be passed to _lsp_to_vim (they are correctly indexed, or at least indexed the way the receiving functions expect it); if you do, you need to decrement the result:
```viml
             \ 'viewstart': lsp#utils#position#_lsp_to_vim(l:path, a:loc['targetRange']['start'])[0]-1,
             \ 'viewend': lsp#utils#position#_lsp_to_vim(l:path, a:loc['targetRange']['end'])[0]-1,
```
That fixes it for me without breaking other functionality.

**Comment by prabirshrestha** [comment]
@clason Feel free to send a PR. Ok to use directly but let us make sure we comment it. Coz one of my goals in future is to start adding tests, hence I have started refactoring it into small functions that we can test without spawning an entire langserver.

**Comment by clason** [comment]
That's an excellent goal :+1: The problem seems to be that different functions expect different indexing, so incremental refactoring is... hard.

**Pull request merged**
