### PR TITLE
Fix text edit when insert empty new text

### PR DESCRIPTION
**Pull request by mikoto2000**
See: #383.
I fixed it.

Do you think that the added test is enough?

### CODE REVIEW

**Comment by prabirshrestha** [comment]
The test wouldn't scale. Is it possible to come up with more generic pattern?

Here is something I can think of.

```
It insert newText
    call s:set_text(['foo', 'bar'])
    call lsp#utils#text_edit#apply_text_edits(...)
    Assert Equals(s:get_text(), ['foo', 'bar', ''])
End
``` 

Also might be worth using a brand new buffer so can also verify cursor for other tests. Makes it easier.

**Comment by mikoto2000** [comment]
I Fixed.

- create new buffer each test
- add test utility function `s:set_text` and `get_text`

`let l:buffer_text = s:get_text()` is error workaround.
(https://github.com/prabirshrestha/vim-lsp/pull/384/commits/52458a2984da7c48f88f8e27fe3d04d9d2079b2e#diff-14b65db95967c47f28c2683e9cdcccbbR46)

I got an error if `Assert Equals(s:get_text(), ['foo', 'bbazar', ''])`.

```
not ok 21 - lsp#utils#text_edit lsp#utils#text_edit#apply_text_edits insert newText
# function 129() abort dict  Line:5  (~/AppData/Local/Temp/VIE246D.tmp)
# function <SNR>13_eval(expr, scopes) abort  Line:11  (~/project/dotvim/.vim/pack/test/opt/vim-themis/autoload/themis/helper/command.vim)
#
# Vim(return):E117: Unknown function: s:get_text
```

vim-themis called `s:get_text` in `command.vim`, so cannot found this.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Comment by mikoto2000** [comment]
Thank you for reviewing and merging!

**Pull request merged**
