### PR TITLE
Semantic tokens performance improvements

### PR DESCRIPTION
**Pull request by frankplow**
The initial implementation of semantic tokens was quite slow. This PR contains some tweaks to improve its performance.

Not currently addressed by this commit is this: at present the function to apply the highlights to the file removes _all_ the highlights from the file and then re-adds them, not those which have just been modified. This is because, according to the vim profiler, the majority of the time is spent decoding the tokens rather than applying them. A "smarter" algorithm which only removes the highlights which change in some way may have to decode the tokens twice, and so even be slower. That being said, I'm not all that confident in vim's profiler so it may be worth verifying this.

A lua rewrite of at least part of this code is probably the most sensible way to get any further performance out if it, but in the meantime these little changes seem to make a noticeable difference.

### CODE REVIEW

**Comment by frankplow** [comment]
Looks like `charidx` and `byteidx` are unsupported by the vim version the checks are running on. I can revert d3655b7 but feel there’s a decent case to depend on them - they were added in c. vim 8.3, in mid-2020, and contribute a ~50% performance improvement on the old method, which is substantial as the `lsp_to_vim` calls account for the majority of the time spent in semantic tokens.

**Comment by prabirshrestha** [comment]
you could try shimming the functions or fallback to old pattern if it makes sense.

https://github.com/prabirshrestha/vim-lsp/blob/278f72d21cd0767b9f1e2de4cd52fa606817a6aa/autoload/lsp/internal/ui/quickpick.vim#L451-L459

There are folks who use stock ubuntu's vim and those usually doesn't get updated frequently.

Another option would be to check the if the function exists else always disable the feature at https://github.com/prabirshrestha/vim-lsp/blob/eb542a379fbb8147ac8ae346f50217df655acc1d/autoload/lsp/internal/semantic.vim#L11.

**Comment by frankplow** [comment]
Reverted d3655b7 for now. I tried shimming it as suggested but it doesn't have quite the same behaviour as the `strchars/strlen` solution (when the index exceeds the length of the input). Adding all the logic to achieve parity between the two outweighed any performance benefit - the margins are very slim here, it only matters as the function gets called many times in semantic tokens.

Sorry for the all the force-pushes, very fat fingers today.

**Comment by prabirshrestha** [comment]
Merged. Thanks!

**Pull request merged**
