### PR TITLE
diagnostics list can be v:null

### PR DESCRIPTION
**Pull request by mattn**
Ref #1186

### CODE REVIEW

**Comment by rhysd** [comment]
I just grepped around the repository and found more places which might need to be fixed:

- https://github.com/prabirshrestha/vim-lsp/blob/61916a2ddd454308cc6f8413d6b8becc5c956917/autoload/lsp/internal/diagnostics/movement.vim#L174
- https://github.com/prabirshrestha/vim-lsp/blob/61916a2ddd454308cc6f8413d6b8becc5c956917/autoload/lsp/internal/diagnostics/movement.vim#L178
- https://github.com/prabirshrestha/vim-lsp/blob/61916a2ddd454308cc6f8413d6b8becc5c956917/autoload/lsp/internal/diagnostics/state.vim#L166

Would you check them?

**Review by rhysd — CHANGES_REQUESTED** [review]
https://github.com/prabirshrestha/vim-lsp/pull/1190#issuecomment-856904226

**Comment by mattn** [comment]
@rhysd Thank you. Fixed

**Review by rhysd — APPROVED** [review]
Thank you for the fixes. Looks good.

**Comment by mattn** [comment]
Merging. I will fix if still have same issue.

**Pull request merged**
