### PR TITLE
Expose diagnostics count for current buffer.

### LINKED ISSUE #346: Statusline Support
I'm not sure if vim-lsp has this but other lsp like ale or coc has a way of showing in the statusline (airline, lightline, etc) at what line an error was encountered. I have read the help file from vim.lsp but i wasn't able to find anything about statuslines. Is there a way to get a similar behavior?.

Thanks for this awesome plugin btw.

### PR DESCRIPTION
**Pull request by tsufeki**
Adds `lsp#get_buffer_diagnostics_counts()` which returns dict with counts keyed by diagnostic kind.

Closes #346

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Based on the comments from @Camotubi

> Almost. The only thing left is the line number of the first error in the current buffer, but I think I can live without that. Should I close this issue?

**Comment by tsufeki** [comment]
Added `lsp#get_buffer_first_error_line()`

**Comment by Camotubi** [comment]
Working like a charm. Thanks @tsufeki

**Comment by Camotubi** [comment]
Tested with neovim 0.3.5 with rls for rust.

**Comment by Camotubi** [comment]
This could serve as a starting point on airline. 
```
let g:airline_section_warning = '%{lsp#get_buffer_diagnostics_counts()["warning"]}'
let g:airline_section_error = '%{lsp#get_buffer_diagnostics_counts()["error"]}%{lsp#get_buffer_first_error_line()? "-".lsp#get_buffer_first_error_line():""}'
```

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
