### PR TITLE
Fix lsp#utils#text_edit#apply_text_edits when end position was newline character.

### PR DESCRIPTION
**Pull request by mikoto2000**
See: #386. I fixed it.

But there is still one problem the last line cannot delete.
https://github.com/prabirshrestha/vim-lsp/blob/4cdfaa93b558a17990373b5a93cfe9b0ba63e0cc/test/lsp/utils/text_edit.vimspec#L234-L256

Do you have any solution or workaround?

### CODE REVIEW

**Comment by mikoto2000** [comment]
Sorry, I was forget deleting debug log code. I force-pushed.

**Comment by mikoto2000** [comment]
I was forget check Range specification...
(https://microsoft.github.io/language-server-protocol/specification)

> A range in a text document expressed as (zero-based) start and end positions. A range is comparable to a selection in an editor. Therefore the end position is exclusive. If you want to specify a range that contains a line including the line ending character(s) then use an end position denoting the start of the next line.

I will fix it. Please wait.

**Comment by mikoto2000** [comment]
@prabirshrestha
I fixed and added tests.
Is this behavior in your expected?

**Comment by maticz** [comment]
I have been using code from @mikoto2000 's pull request for some time now and it works well. Are there plans to merge it?

**Comment by prabirshrestha** [comment]
Merged. Thanks for the PR.

**Pull request merged**
