### PR TITLE
Always show the kind and name in CallHierarchy

### PR DESCRIPTION
**Pull request by daisuzu**
#1113 improved the quickfix.
But the output of `gopls` looks like this due to the current implementation([v0.6.9](https://github.com/golang/tools/blob/gopls/v0.6.9/internal/lsp/source/call_hierarchy.go#L291)).

```
internal/lsp/source/identifier.go|57 col 6| golang.org/x/tools/internal/lsp/source • identifier.go
```

So, fix to show the kind and name as follow.

```
internal/lsp/source/identifier.go|57 col 6| [function] Identifier: golang.org/x/tools/internal/lsp/source • identifier.go
```

After(rust):

```
src/lib.rs|1 col 1| [function] get_two: fn get_two() -> i32
```

### CODE REVIEW

**Review by rhysd — APPROVED** [review]
Looks good to me.

**Comment by rhysd** [comment]
I want one more approval from other maintainers.

**Comment by hrsh7th** [comment]
- Before
    - `%DETAIL%` or `[%KIND%] %NAME%`

- After
    - `[%KIND%] %NAME%: %DETAIL%`

LGTM.

**Review by hrsh7th — APPROVED** [review]

**Comment by daisuzu** [comment]
Thanks!

**Pull request merged**
