### PR TITLE
Expand avenues to access diagnostics

### PR DESCRIPTION
**Pull request by paradigm**
* Add plug mapping and command to echo diagnostic under the cursor.

* Add plug mapping and command to preview/float diagnostic under the cursor.

* Add variable to to automatically echo diagnostic after jumping to it
with a next/previous diagnostic command.

### CODE REVIEW

**Comment by paradigm** [comment]
This PR implements all of features proposed in https://github.com/prabirshrestha/vim-lsp/issues/1074.

As noted in https://github.com/prabirshrestha/vim-lsp/issues/1045 and https://github.com/prabirshrestha/vim-lsp/issues/1047, vim-lsp's implementation of the preview window is currently broken, and so I could not meaningfully test this functionality with `g:lsp_preview_float = 0` or older versions of vim which lack `popup_create()`.

Please let me know if there's anything I should change.

**Comment by paradigm** [comment]
My initial logic to echo after `<plug>(lsp-previous-diagnostic)` was off by one diagnostic.  My latest pushed fixed it.

**Comment by paradigm** [comment]
My initial logic apparently also failed to handle wrapping.  My latest push fixed that as well.

**Comment by paradigm** [comment]
I can't see any way my PR would affect document formatting.  Is there any chance the test broke as a result of nightly neovim changes breaking vim-lsp master?  If not, and this is my PR, I'd be happy to fix it if I'm provided a bit of guidance on where to dig.

**Comment by paradigm** [comment]
I am lost as to how a24eaec passes but 20301d1 breaks `LspDocumentFormatSync` tests.  Moreover, I find the fact that `linux_vim` fails where `linux_neovim` and `mac_vim` succeed is strange; same for `mac_neovim` failing where `linux_neovim` and `mac_vim` pass.  Is there any chance this is a test flake?

If not I'll be happy to try and fix it, but I might need to be pointed more closely in terms of where to dig.

**Comment by paradigm** [comment]
After a bit more digging, I found the latest commit in master, a78536ad745852c73cdf2d0defffd6b81bc377f0, [also failed this same test](https://github.com/prabirshrestha/vim-lsp/runs/1952317131) despite also not doing anything remotely related to formatting.  I figure since that was merged, this is a known flake.

As far as I can tell on my end, this PR is good to go.  Please let me know if there's anything I should change to help this get merged.

**Comment by prabirshrestha** [comment]
I need to get rid of the integration test. It hasn't been stable. Ideally we need to have async tests support in themis.

**Comment by paradigm** [comment]
Anything I can do to help expedite getting this merged?

While I understand a need for patience around these things, maintaining a fork and regularly fixing rebase conflicts is a bit tedious.

**Comment by paradigm** [comment]
See you again in August, stale bot.

**Comment by paradigm** [comment]
Still here

**Pull request closed without merging**
