### PR TITLE
Search for multiple file/dir names in lsp#utils#find_nearest_parent_file_directory

### PR DESCRIPTION
**Pull request by IceNature**
Implement a `lsp#utils#find_nearest_parent_file_directory` for #124 
This function now supports both List and String `filename` argument.
The filename ending with '/' or '\' will be regarded as directory name, otherwith as file name.
It will return a path which is found the most times. If there is a directory in `/home/test/project`, for example
```
+ .git/
- src/
      CMakeLists.txt
      main.cpp
      ....
  .ccls
  CMakeLists.txt
  compile_commands.json
```
Call the function with a buffer opened in `src/` directory
```viml
lsp#utils#find_nearest_parent_file_directory(lsp#utils#get_buffer_path(), ['.ccls', 'CMakeLists.txt', 'compile_commands.json', '.git/', 'README.md'])
```
It will return `/home/test/project`
But if there are more than one paths with same max count, it will return the one which has the lowest index of the list. How about return the longest path string?

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Can we add tests for this?

**Comment by prabirshrestha** [comment]
Could you also update the doc?

**Comment by IceNature** [comment]
The doc was added into README.md, for I don't fint any doc about `lsp#utils#find_nearest_parent_file_directory` in `doc/vim-lsp.txt`.

**Comment by prabirshrestha** [comment]
Feel free to create new doc in `doc/vim-lsp.txt`. We shouldn't add it in README.md. README.md was before we had `doc`.

**Comment by IceNature** [comment]
The document has been moved into `doc/vim-lsp.txt`

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
