### PR TITLE
Fix hover syntax

### LINKED ISSUE #576: LspHover text highlight/format
Not sure if this is intended or I do miss some setup.

Here underscore is highlighted
image

Here almost everything is _italic_
image

OS: win10
Gvim: 8.1.2337

### PR DESCRIPTION
**Pull request by thomasfaingnaert**
Fixes #576

### CODE REVIEW

**Comment by thomasfaingnaert** [comment]
@prabirshrestha Windows CI still seems to be broken, by the way. Even on new PRs.

**Comment by prabirshrestha** [comment]
I noticed that. Will look at it again when I'm free.

In the mean time can you paste the before/after screenshots.

**Comment by thomasfaingnaert** [comment]
Before:
image


After:
image

**Comment by thomasfaingnaert** [comment]
The escaping of the `*` seems to be a quirk of pyls, so maybe we shouldn't touch escaped chars. As for the `_` that is highlighted as an error, I still think that's a good idea, as `markdownError` is not useful when rendering markdown in hover?

**Comment by thomasfaingnaert** [comment]
@prabirshrestha What are your thoughts on this? Disabling highlighting of errors seems fine, but I'm not sure we should hide the escape sequences. The lsp spec also doesn't specify how clients should handle escapes either.

**Comment by prabirshrestha** [comment]
Can we only enable this for some language servers via config? given that we have https://github.com/mattn/vim-lsp-settings it should be simple to only set the config there so others don't need to worry about it.

But this also is syntax so would be difficult to get the language server name there.

I'm ok with the latest changes you have.

**Comment by prabirshrestha** [comment]
Also might be good to comment the bug in code. so we can remove it once fixed by them. https://github.com/palantir/python-language-server/issues/386

that could be the most simple workfaround for now without trying to do this per language.

I personally prefer not to have hack per language server but this does seems irritating to people who use it.

Thoughts?

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Comment by thomasfaingnaert** [comment]
It is indeed annoying that this is only really needed for pyls. I think it's fine to enable this for all language servers, since the hover is supposed to be "rendered" in the client, so I'm fine with merging this as-is.

**Pull request merged**
