### PR TITLE
fix broken rename command 

### PR DESCRIPTION
**Pull request by studiome**
@markuspeloquin  found this solution to make rename command works good. LspRename failed to start by E716 error (dictionary key not found).

### CODE REVIEW

**Comment by prabirshrestha** [comment]
This wouldn't work for all. you would need to handle all these cases based on the spec. https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename

```
Range | { range: Range, placeholder: string } | { defaultBehavior: boolean } | null
```

```
let l:range = a:data['response']['result']['range']
```

```vim
if empty(a:data['response']['result'])
   " it null
elseif type(a:data['response']['result']) == type({})
   " result is type of dict
   if has_key(a:data['response']['result'], 'range')
      " `{ range: Range, placeholder: string }`
   elseif has_key(a:data['response']['result', 'defaultBehavior')
      " `{ defaultBehavior: boolean } `
   else
      " `Range`
   endif
endif
```

Do has more info on how to handle each case.

This is probably because [a85b71bfc862753ee11ae5986d882bd9588b17a2](https://github.com/prabirshrestha/vim-lsp/commit/a85b71bfc862753ee11ae5986d882bd9588b17a2) started sending `'prepareSupportDefaultBehavior': 1` and is breaking. one option would be to disable the flag and see if it works. It would still be good to support this flag.

**Comment by studiome** [comment]
Thank you so much @prabirshrestha . I could learn LSP more.

**Comment by tsukkee** [comment]
Thank you for your fixing this.

In #1379, I added two options to `rename` capability.
* `prepareSupport`: with this capability, `textDocument/prepareRaname` is sent and I found its return value can be both `Range` or `{ range: Range }`. For example, volar (LSP server for Vue) returns `Range` and gopls returns `{ range: Range }`
* `prepareSupportDefaultBehavior`: I'm sorry but I don't understand details for this... but I assume that this will cause `{ defaultBehavior: boolean }` pattern according to its name.

So, I think possible solution might be...
* handle `Range | { range: Range, placeholder: string } | null` case in `s:handle_rename_prepare()`
* delete `prepareSupportDefaultBehavior` from default capability to avoid `{ defaultBehavior: boolean }`

**Comment by studiome** [comment]
Thank you for your commitment of this issue, @tsukkee .

**Comment by hrsh7th** [comment]
I'll look into it to this problem.

@studiome Can i make another PR...?

**Comment by prabirshrestha** [comment]
Fixed by https://github.com/prabirshrestha/vim-lsp/pull/1387

**Pull request closed without merging**
