### PR TITLE
Reduce flickering during sign update

### PR DESCRIPTION
**Pull request by tsufeki**
Set `&signcolumn` during update to reduce flickering.

I also fixed adding sign for diagnostic without severity: in the LS protocol severity is optional.

### CODE REVIEW

**Comment by xtal8** [comment]
Vim 7.4.2201 added 'signcolumn' option. Could it be used instead of adding dummy sing?

**Comment by prabirshrestha** [comment]
Sure. We depend on vim8 and neovim with timers and lambda so most of them should already have that patch.

**Comment by tsufeki** [comment]
I make the changes. I'm not sure this is the simplest solution, so I'm open for suggestions.

**Comment by prabirshrestha** [comment]
@xtal8 do you have better solution then what is implemented here?

**Comment by xtal8** [comment]
Sorry, I don't know much about signs feature to be of help.

**Comment by pdavydov108** [comment]
Before I used ycm and almost never had similar issues with it. So I've checked how ycm sets signs. I've noticed two things. First, when ycm gets new signs, [it doesn't delete old signs first](https://github.com/Valloric/YouCompleteMe/blob/788c293aee78c6ab60cbc06bbc3339e7b2bff98f/python/ycm/diagnostic_interface.py#L176). It iterates throw all signs that were set before, then adds new signs, and then, in the end remove those that were set before and are not present in the latest server response. Second, it feels like ycm is only placing signs when user leaves insert mode. This makes sense, at least for c++/cquery. Cquery is pretty fast, so when I start typing `boost` it shows that it's a compilation error, then I add `:`, so it becomes `boost:` which is a valid syntax, cause it is treated as goto label (goto can screw things up even if we don't use it :) ). So cquery immediately sends message to remove all error signs. Users (at least those who type as slow as me) will see it as flickering, cause last sign is removed, vim hides sign column, then shows it again with new error, cause user adds another `:`. I've started implementing signs merging to check if it will help with flickering, I'm testing it now. One issue with it is that it's a bit more complex then current algorithm. What do you think about merging signs? I'm not sure how and when vim decides to hide signcolumn, so I don't know what cases of flickering will it cover. Maybe we can (optionally?) update sings only on exit from insert mode? Does anybody benefit from diagnostics on every letter they type?

**Comment by prabirshrestha** [comment]
With [vim 8.1.0614](https://github.com/vim/vim/commit/162b71479bd4dcdb3a2ef9198a1444f6f99e6843#commitcomment-31766280) from this PR https://github.com/vim/vim/pull/3652, there are new sign apis which will make it easier to maintain the signs. I think we should make use of that api instead. For older vim we can remove support for sign/diagnostics. Given that vim-lsp is primarily used in dev machines, I don't think any one will have issue updating vim if they want this support.

**Comment by prabirshrestha** [comment]
I have started the work on redoing the sign columns using new vim api. Can you try this out - https://github.com/prabirshrestha/vim-lsp/pull/294

Let me know if you still see the flickering issue.

**Comment by prabirshrestha** [comment]
Please try the latest master. We have now redone the diagnostics.

**Pull request closed without merging**
