### PR TITLE
Prepare range for rename

### PR DESCRIPTION
**Pull request by mattn**
Related to https://github.com/prabirshrestha/vim-lsp/issues/212

Vim does not know which range will be replaced while rename. And `expand('<cword>')` is depend on `iskeyword` option of vim. So resolve range for the rename.

### CODE REVIEW

**Comment by mattn** [comment]
Do not merge since `input("new name", a:old_name)` does not work correctly. Probably, this is a bug of input() of vim.

**Comment by mattn** [comment]
https://github.com/vim/vim/pull/3809

**Comment by prabirshrestha** [comment]
Do we need to wait for the vim patch or this is good enough?

**Comment by prabirshrestha** [comment]
Feel free to merge. Also might be worth tackling https://github.com/prabirshrestha/vim-lsp/issues/121 so we flush after rename is complete.

**Pull request merged**
