### PR TITLE
Fix textEdit check

### PR DESCRIPTION
**Pull request by hrsh7th**
This PR fixes the completion confirmation problem.

https://github.com/prabirshrestha/vim-lsp/pull/908#issuecomment-703295489

### CODE REVIEW

**Comment by prabirshrestha** [comment]
This works. Thanks for the quick fix.

I do see this though.
image

**Comment by hrsh7th** [comment]
Thank you for your confirmation.

I've fixed for echo message.

**Comment by prabirshrestha** [comment]
Works. Feel free to merge.

Appreciate the quick fix.

**Comment by hrsh7th** [comment]
Sorry for my mistake... Thank you again for your confirmation

**Pull request merged**
