### PR TITLE
Add support for client-side commands

### PR DESCRIPTION
**Pull request by dradtke**
The eclipse.jdt.ls project implemented workspace edits using custom
client-side commands, apparently due to an ambiguity in the spec. As a
result, other clients have had to implement these custom commands.

The only one implemented in this commit is `java.apply.workspaceEdit`,
though there are other ones that can be added on an as-needed basis.

See https://github.com/eclipse/eclipse.jdt.ls/issues/376#issuecomment-333923685

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Unfortunately we can’t merge this since it isn’t generic. Instead we should have a hook so that other can implement this.

**Comment by dradtke** [comment]
Are there any plans to support extensions of some sort? This could be extracted to a separate plugin like `vim-lsp-java`, but it would need to be able to access `vim-lsp`'s ability to execute commands and receive the results.

**Comment by prabirshrestha** [comment]
@dradtke If someone send a PR I'm more than happy to merge hook support. 

I have been thinking of something like this.

```vim
function! s:handle_code_action(opt) abort
    if a:opt['server_name'] == 'java'
         " do custom code
         return 1 " handled
    endif
   return 0 " not-handled
endfunction

let l:id = lsp#register_hook('textDocument/codeAction', function('s:'handle_code_action'))
call lsp#unregister_hook(l:id)
```

Another option is to add it as part of `register_server`.
```vim
lsp#register_server({
    \ 'cmd': ['...'], 
    \ 'hooks': {
    \     'textDocument/codeAction': function('s:handle_code_action') 
    \ }  
    \ })`
```

Need to finalize how `register_hook` looks like. Should that be before request or after request? Or should it be explicit `on_request:textDocument/codeAction`, `on_response:textDocument/codeAction`.

Plugins like `vim-lsp-java` or [vim-lsp-settings](https://github.com/mattn/vim-lsp-settings) can then register hooks. The primary reason I do not want it to be inside vim-lsp is that I will have to keep maintaining lot of one of requests for many languages that I do not use and I will not be the best person to do so.

**Comment by dradtke** [comment]
I'm open to either of your design suggestions, leaning more towards the former because it would allow `vim-lsp-java` to just work assuming the user has already configured the Java language server with `vim-lsp`.

**Comment by dradtke** [comment]
Closing in favor of https://github.com/prabirshrestha/vim-lsp/pull/693.

**Pull request closed without merging**
