### PR TITLE
Extension: Add support for clangd switch header/source

### PR DESCRIPTION
**Pull request by kent-tri**

### CODE REVIEW

**Comment by mattn** [comment]
Thanks your contribution. But textDocument/switchHeader is not appear in standard language server specification. So I think we should not add this feature.

**Comment by thomasfaingnaert** [comment]
As @mattn said, this is specific to one language server, and we would like vim-lsp to stay as LSP server agnostic as possible.

@mattn Can we move things like this to https://github.com/mattn/vim-lsp-settings?

**Comment by kent-tri** [comment]
@mattn @thomasfaingnaert makes sense to me and I agree. I'll close this out and when I get a free minute will think more about how best to build a plugin system either in `vim-lsp-settings` or as a separate project that would be a better place to store these service-specific extensions.

**Comment by mattn** [comment]
I will consider to add this positively.

**Pull request closed without merging**
