### PR TITLE
Option to always open a new tab when going to new locations

### PR DESCRIPTION
**Pull request by robz**
I prefer to open new tabs when navigating. Not sure if anyone else would like this, but I thought I'd throw up a pull request just in case.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
For workaround I would use this instead.

The problem with having one flag is what about splits?

https://github.com/prabirshrestha/vim-lsp/issues/169#issuecomment-419720171
```vim
nmap \gd :LspDefinition<cr>
nmap \gt :tab split<cr>:LspDefinition<cr>
nmap \gs :sp<cr>:LspDefinition<cr>
nmap \gv :vsp<cr>:LspDefinition<cr>
```

I would be happy to accept PRs that does this instead. `:LspDefinition --opener vsplit` or `:LspDefinition --opener tab` with `let g:lsp_definition_config = { 'opener': 'tab' }`. There are also ask if there is only one definition people want to jump directly and if there are more use either loclist or quickfix. I need to lockdown the api before we actually implement it.

**Comment by argoncloud** [comment]
This feature would be great. In the meantime, there is another viable approach using the QFEnter plugin, which allows one to open the quickfix entry selected in the current split, in a new horizontal split, in a new vertical split, or in a new tab.

**Comment by mattn** [comment]
@prabirshrestha it's useful. but when the definition is not found, the buffer will be remaining.

**Comment by robz** [comment]
Since making this pull request, I've become a lot more comfortable using buffers directly instead of tabs. Closing this out.

**Comment by prabirshrestha** [comment]
This is now possible with `<mod>` which is the vim way. https://github.com/prabirshrestha/vim-lsp/pull/776

`:tab LspDefinition` Opens a window to the new tabpage.

**Pull request closed without merging**
