### PR TITLE
add basic .travis.yml

### PR DESCRIPTION
**Pull request by prabirshrestha**
testing CI

### CODE REVIEW

**Comment by mattn** [comment]
Do you have ideas to test vim-lsp that doing communicating to the server asynchronoslly?

**Comment by prabirshrestha** [comment]
I have not thought of it yet. Currently interested in linting and sync methods. For example I can get make the response from LSP server and test that. Can you give an example method that you want to test? We might need to call wait for. Also would be good to see how in vim they test async methods. Don't they just have a while loop that waits for some condition?

In long run might be worth moving the async methods to use Rx Observables or Promises from vital.vim, this will make it easy to deal with async code but not sure about tests.

**Comment by mattn** [comment]
I prefer to add code that is used from tests into autoload/*. If it is difficult, we can do this (but ugly)

```go
package main

import "fmt"

func main() {
    fmt.
}
```

```vim
new test_001_completion.go
setlocal completeopt=
let l:pos = getpos('.')
let l:pos[1:2] = [6:8]
call setpos(l:pos)
sleep 1 " wait enough until initialization
startinsert!
call feedkeys('\<c-x>\<c-o>')
sleep 1 " wait enough to get response
call feedkeys('\<c-n>')
```

**Comment by prabirshrestha** [comment]
Can we do something like vim tests? https://github.com/vim/vim/blob/master/src/testdir/test_job_fails.vim

Calling `WaitFor` is a common practice even in the web for selenium tests where we can't guarantee when it will be available. So it keeps retrying multiple times until it times out.

```vim
source shared.vim

func Test_job_start_fails()
  if has('job')
    let job = job_start('axdfxsdf')
    if has('unix')
      call WaitForAssert({-> assert_equal("dead", job_status(job))})
    else
      call WaitForAssert({-> assert_equal("fail", job_status(job))})
    endif
  endif
endfunc
```

We could most likely just copy the function from vim source

**Comment by mattn** [comment]
Sounds good to me. Do you trying to install pyls?

**Comment by prabirshrestha** [comment]
I'm ok install any lang server for tests like pyls.

Currently have just vint working for osx and linux. Trying to get it work for windows for few more mins. If not I can get it just for those two os so we can start getting tests enabled for those OS.

**Comment by prabirshrestha** [comment]
@mattn This PR is now ready for merge. It runs on linux and mac. But vim version is older. But we should be able to start writing basics tests. Let me know if you have any preference for test frameworks.

**Pull request merged**
