### PR TITLE
completion/resolve support for documentation and use the new floating window

### PR DESCRIPTION
**Pull request by prabirshrestha**
Redo completion documentation popup using the new vital floating window api. This is very much WIP and is lacking lot of features.

- [x] fix popup position
- [ ] add focus support
- [ ] add scroll support
- [x] add ft
- [x] add readonly
- [x] add highlights
- [ ] ~~add dock support~~
- [x] add autocmd `lsp_float_opened`
- [ ] add/update documentation

This is very much work in progress and popup doesn't show correctly. @hrsh7th Feel free to push changes to this branch based on your apis. Currently I'm looking into using the api correctly. Few questions for you.

- [x] Should we re-use window/buffer instead of creating a new one?
- [x] Need to add markdown support. (if we do this we need to make sure we update lsp.vim to add markdown support in client capabilities)

Really looking for simplifying popup/floating window and be consistent with both vim and neovim.

### CODE REVIEW

**Comment by hrsh7th** [comment]
> Should we re-use window/buffer instead of creating a new one?
Yes. IMO, we should re-use `buffer` per floating window.
I will push changes into this branch.

> Need to add markdown support. (if we do this we need to make sure we update lsp.vim to add markdown support in client capabilities)
It can be supported with vital-vs. I will push it.

**Comment by hrsh7th** [comment]
IMO, we should implement `lsp#internal#ui#floating_win` for solve conflicts multiple floating window.
For example, the diagnostics can be shown by floating-window but if the user requests hover, it should be removed automatically. it means the `floating_win` should have the priority and it close automatically when opened more highly priority window.

**Comment by prabirshrestha** [comment]
@hrsh7th Feel free to modify or work in different branch. Which ever you are comfortable with.

When I worked on my vital.vim popup my thought was to have a higher level popup manager so we can coordinate.  Your example is a good one. We most likely need a higher level api to specify type of floating window such as diagnostics/hovers/completion docs. Some of these can even be docked. My branch most likely doesn't make sense here. Fell free to suggest the new api to use.

**Comment by prabirshrestha** [comment]
I'm merging for now. Rest can come later.

Few things we would need to fix:
1. Focusing 
2. Scrolling
3. transparency bug in vim only
4. border
5. dock to preview. I think we can use preview window directly without floating window for this case. (I personally don't use this so it would depend on demand)

I personally don't use focus/scrolling for completion but use it for hover so we would need to fix it when we migrate hover.

@hrsh7th thanks for your vital floating window popup and your contribution in this PR.

**Comment by subnut** [comment]
On Neovim 0.4.4 -

gifcast_210123180713

Are the following intended behaviour?
- One letter-width spacing between completion pum and documentation pum
- Documentation pum using only half of the window width

**Comment by prabirshrestha** [comment]
I will let @hrsh7th comment on it but currently it is `'maxheight': float2nr(&lines * 0.4),`. Based on your example it does seem like we could have it be taller.

**Comment by hrsh7th** [comment]
> One letter-width spacing between completion pum and documentation pum

It's intentional by me. But it up to the personal taste... (feel free to send PR if you want to change).

In my opinion, `One letter-width spacing` is better to have. because the completion-menu and floating-window(neovim) have no borders so the spacing will be used as a separator.

> Documentation pum using only half of the window width

It's a problem. I will send PR for it.

**Comment by clktmr** [comment]
> dock to preview. I think we can use preview window directly without floating window for this case. (I personally don't use this so it would depend on demand)

I preferred the ability to use the preview window for documentation of completion items because:
- documentation always showed up at the same location and not cover any other code
- it will stay open after completion for reference
- is easier to focus/navigate without mouse

Support for this would be much appreciated 🙏

**Pull request merged**
