### PR TITLE
Add title to Lsp(Document|Workspace)Symbol quickfix window

### PR DESCRIPTION
**Pull request by obcat**
Enables user to get a more helpful title for Lsp(Document|Workspace)Symbol quickfix window via `w:quickfix_title`.

#### Before

vim lsp pull-req before

#### After

vim lsp pull-req after

### CODE REVIEW

**Comment by prabirshrestha** [comment]
This will break older version of vim. We need to do a version check.

**Comment by mattn** [comment]
Please fix like:
```
if has('patch-8.2.2147')
    call setqflist(l:list)
    call setqflist([], 'a', {'title': a:type})
else
    call setqflist([])	
    call setqflist(l:list)
endif
```

**Comment by obcat** [comment]
I'm sorry for delay in responding.

I followed advice and updated.
Please could you review?

**Comment by mattn** [comment]
Thank you.

**Comment by obcat** [comment]
Thank you for merging!

**Pull request merged**
