### PR TITLE
Changed Quickfix list behaviour

### PR DESCRIPTION
**Pull request by lkebin**
At this before, lsp commands will clean current Quickfix list and create
a new one. This will cause some trouble, e.g.: when we have search result
in Quickfix list, but if we do :LspDefinition jump to symbol definition, the Quickfix list will
be empty.

Now, let :Lsp* commands just replace Quickfix list when the results need
to display on Quickfix list

### CODE REVIEW

**Comment by prabirshrestha** [comment]
`'r'` doesn't work when there are multiple providers that may return values. Basically we need to look at the counter and if it is the fist one call replace else append.

also be careful with older version of vim that may not support it. I'm ok with not handling this case and when someone files a bug we can looking into it.

**Comment by lkebin** [comment]
Hi @prabirshrestha, thanks for your feedback.
I just removed 'r' behavior, but delayed the `empty` action.

**Comment by lkebin** [comment]
Hi @prabirshrestha @mattn, could please you merge this PR ?

**Comment by mattn** [comment]
make sense to merge this.

**Comment by prabirshrestha** [comment]
@lkebin could you fix the merge conflicts?

**Comment by lkebin** [comment]
> @lkebin could you fix the merge conflicts?

Ready to merge now.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
