### PR TITLE
Support show message notification by handling `window/showMessage` response

### PR DESCRIPTION
**Pull request by rhysd**
This PR adds support for [ShowMessage Notification](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#window_showMessage)

> The show message notification is sent from a server to a client to ask the client to display a particular message in the user interface.

This support is necessary to know the results of Code Lens with gopls.

I confirmed this PR worked fine on my local as follows:

tmp

(`"log"` is set to `g:lsp_show_message_log_level`)

TODO:

- [x] Add tests

### CODE REVIEW

**Comment by mattn** [comment]
LGTM but pass to another look.

**Comment by mattn** [comment]
I played with this and this works fine for me. So merging.

**Comment by mattn** [comment]
Thank you

**Comment by mattn** [comment]
@rhysd Ah, I forgot to check whether this change break (or not break) input(). Did you check this feature does not need to call inputsave/inputrestore?

**Comment by rhysd** [comment]
@mattn I did not care about `inputsave`/`inputrestore`. As far as I tried this branch, I didn't see any problem on editing the text buffer while vim-lsp outputs server messages by `:echom`. But it might be safer to add `inputsave`/`inputrestore` before/after outputting a message.

**Pull request merged**
