### PR TITLE
Set meaningful title to QuickFix window instead of ":setqflist()"

### LINKED ISSUE #293: :LspDefinition will display an empty quickfix
Hello.
vim-lsp is a great plugin. thank you.

I have points that I want you to correct about quickfix set by `:LspDefinition`.
I often display the result of the grep command in quickfix, but when I run `:LspDefinition`, an empty quickfix is displayed.
In this case need to run `:colder` to display the previous quickfix. I think this is undesirable.

I guess that the reason is that you have set an empty quickfix in the following places
https://github.com/prabirshrestha/vim-lsp/blob/043340455683463a3c8f854b7ac4bdfed70089d9/autoload/lsp/ui/vim.vim#L34

### PR DESCRIPTION
**Pull request by Jorengarenar**
This is basically a continuation and generalization of solution from PR  #936

Additionally it'll probably also fix #293 and #1483

### CODE REVIEW

**Comment by Jorengarenar** [comment]
@prabirshrestha Could you have a look? :)

**Comment by Jorengarenar** [comment]
@prabirshrestha Looks good to merge?

**Comment by Jorengarenar** [comment]
@prabirshrestha @mattn Looks good to merge?

**Comment by Jorengarenar** [comment]
@prabirshrestha @mattn @hrsh7th @thomasfaingnaert @rhysd
Could you please have a look? :)

**Comment by prabirshrestha** [comment]
Merged. Thanks!

**Pull request merged**
