### PR TITLE
Add delay before didSave

### LINKED ISSUE #422: Larger source files cause failure to delete backup files
When saving larger source files, usually 80KB and up, I am often receiving `E207: Can't delete backup file`. This message occurs on the majority of saves including when no changes are made. When this plugin is disabled, the backup files are deleted properly and no error appears.

Here you can see all of the backup files that failed to delete when spamming `:w` a few times:

backup_files

I am using Windows, Neovim, clang, ccls, and a very minimal configuration for testing. All of the diagnostics work normally and this saving issue on large source code is the only major issue.

This is fixable by disabling backups entirely, but this seems like a bad solution.

### PR DESCRIPTION
**Pull request by Crunkle**
Fixes #422 by adding a micro delay before `textDocument/didSave`. On Windows, any language server that memory maps the file can introduce locks that interfere with Vim's saving. This adds a short delay so that repeated saves do not collide with each other or fail due to the previous lock.

I have been using this vigorously for a month and with no issues.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@Crunkle does this work in both vim and neovim? They have different arguments on the callback.

**Comment by Crunkle** [comment]
Yes, it seems to work for both without issues and I have just tested again to confirm so.

The zero milliseconds delay is also well defined by Neovim ([via libuv](http://docs.libuv.org/en/v1.x/timer.html)):

> If timeout is zero, the callback fires on the next event loop iteration.

And similarly, for regular old Vim, it is executed on the next loop iteration: see [here](https://github.com/vim/vim/blob/0a52df50a0e8fce6f5e0eb5f5373dcd0fa24d83a/src/ex_cmds2.c#L152).

The true solution would be for all language servers to avoid memory maps on Windows as they introduce locks that linger slightly too long. This is the smallest patch that fixed it for me for all cases.

Feel free to close if out of scope, but I think it would be a nice patch with no major downsides.

**Comment by mattn** [comment]
Could you please add comment above the line why this code is required?

**Comment by Crunkle** [comment]
Added.

**Comment by mattn** [comment]
LGTM. Pass to prabirshrestha's look.

**Comment by prabirshrestha** [comment]
I'm good with this. If we get bugs we could use this behind a flag.

**Comment by thenewvu** [comment]
Has anyone experienced the issue where vim-lsp is no longer able to update diagnostics on a pretty big file (around 3500 LOC) after a big save? I tried to test some possible commits that may cause this, turn out that it only happens since 3349cdc.

**Comment by prabirshrestha** [comment]
@thenewvu @Crunkle can one you add a flag to this which is disabled by default?

**Comment by thenewvu** [comment]
@prabirshrestha done in #629

**Pull request merged**
