### PR TITLE
Fix unneccesary window splits

### PR DESCRIPTION
**Pull request by d86leader**
This pull request modifies behaviour of all jumping functions. Previously when file was modified, it would always split the window to jump to new location. Now it doesn't split when the location is in the same buffer.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@d86leader could you fix merge conflicts?

**Comment by d86leader** [comment]
Done. I believe there was also a bug in the related pull request #776 , so I fixed that.

Also @prabirshrestha while you're here, would you care to merge a pull-request in another repo? (=
https://github.com/prabirshrestha/async.vim/pull/37

**Comment by d86leader** [comment]
Today I found bugs in my own 3 lines, so I fixed everything for real this time.

**Comment by prabirshrestha** [comment]
Merged both. Thanks.

**Pull request merged**
