### PR TITLE
Add tcp feature

### PR DESCRIPTION
**Pull request by mattn**
https://github.com/prabirshrestha/async.vim/pull/41

image

### CODE REVIEW

**Comment by mattn** [comment]
I'll do AsyncEmbed again after https://github.com/prabirshrestha/async.vim/pull/41 will be merged.

**Review by prabirshrestha — APPROVED** [review]
looks good. added few comments in async.vim pr instead.

**Comment by prabirshrestha** [comment]
We need to also update the doc example.

**Comment by mattn** [comment]
Cause of failing test seems to not related on this PR.
image

**Pull request merged**
