### PR TITLE
[WIP] implement executeCommand

### PR DESCRIPTION
**Pull request by mattn**
I don't know how to use, how to specify arguments.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Might be worth trying with [typescript-language-server](https://github.com/theia-ide/typescript-language-server/blob/9addd3b5c97f553503b4ae1338c51ef2f7a84883/server/src/lsp-server.ts#L144-L150). It supports few` executeCommands`.

```
executeCommandProvider: {
    commands: [
        Commands.APPLY_WORKSPACE_EDIT,
        Commands.APPLY_CODE_ACTION,
        Commands.APPLY_REFACTORING,
        Commands.ORGANIZE_IMPORTS,
        Commands.APPLY_RENAME_FILE
    ]
}
````

There is another for docker too at https://github.com/rcjsuen/dockerfile-language-server-nodejs/blob/7e1d8d4dd08cff4e8aab024ecd6befe6888d76a8/src/dockerCommands.ts

**Comment by prabirshrestha** [comment]
We might also want to support codeAction. This PR had an initial support for it but not merged. https://github.com/prabirshrestha/vim-lsp/pull/211 

https://microsoft.github.io/language-server-protocol/specification#workspace_executeCommand
>The arguments are typically specified when a command is returned from the server to the client. Example requests that return a command are textDocument/codeAction or textDocument/codeLens

**Comment by mattn** [comment]
Ah, I missed that #211 implement executeCommand too.

**Comment by mattn** [comment]
>We might also want to support codeAction.

Do you mean codeLens?

I still not really understand codeLens. What is differnece between #211 and current implementation of codeAction.

**Comment by mattn** [comment]
Added codelens.

**Comment by mattn** [comment]
Still I can not find Language Server that provide useful response of codeLens. Do you know one?

**Comment by prabirshrestha** [comment]
Even I don't have much context on this. For now I'm going to close this PR as part of cleanup. We should be able to see it in PR history in case we want to have a look at this again.

The other way I can think of is using vscode and enable log and see what others are doing.

**Pull request closed without merging**
