### PR TITLE
[WIP] Introduce floatwin/popupwin compatible layer

### PR DESCRIPTION
**Pull request by hrsh7th**
This PR aims to discuss the PR #510.

TODO
- [x] Support fenced language highlighting (difficult...).
- [x] Switch output.vim to new implementation.

Please feedback the APIs and below points.

- How to support `let g:lsp_preview_float = 0`.
- How to support popup-win's border feature.
- Currently implementation always use`markdown` syntax.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Would be also good to have borders for neovim. Can be in different PR https://github.com/neovim/neovim/issues/9718#issuecomment-546603628

**Comment by clason** [comment]
See also https://www.reddit.com/r/neovim/comments/eh397t/a_floating_terminal_plugin_with_border/

**Comment by prabirshrestha** [comment]
Thanks for sending this PR. 

Let us move this to top level `utils` folder instead of `ui/vim`. I will be working on refactoring `ui/vim/vim.vim` into smaller utils. I want to slowly get rid of the `ui` folder.

Here are some of the api name changes we should do.

```vim
let l:floatwin = lsp#utils#floatwin#new({ ... })
call l:floatwin.show(screenpos, lsp#utils#normalize_markup_content(content))
call l:floatwin.hide()
call l:floatwin.enter() " should this be called focus()?
call l:floatwin.is_visible()

call lsp#utils#floatwin#calcaulate_height(contents)
call lsp#utils#floatwin#calcaulate_width(contents)
call lsp#utils#floatwin#screenpos(line, col, bufnr) " do we need bufnr?
```

**Comment by prabirshrestha** [comment]
@hrsh7th any updates on this? currently it has merge conflicts.

**Comment by hrsh7th** [comment]
Sorry, I have forgotten this PR.

Hm... PR has a problem that is missing `preview-window` feature.

Anyway, I will solve conflicts.

**Comment by prabirshrestha** [comment]
let us continue the discussion at https://github.com/vim-jp/vital.vim/issues/747 and https://github.com/vim-jp/vital.vim/pull/748.

**Pull request closed without merging**
