### PR TITLE
Include maintainers information in document

### PR DESCRIPTION
**Pull request by rhysd**
so that users can easily contact to maintainers without making issues on repository (for example, on SNS).

### CODE REVIEW

**Comment by mattn** [comment]
Please add @ thomasfaingnaert.

**Comment by rhysd** [comment]
Ah, thank you for the point. I'll do.

**Comment by rhysd** [comment]
I added Thomas Faingnaert and rebased this branch onto the latest master.

**Comment by mattn** [comment]
LGTM. Feel free to merge. Thanks.

**Review by mattn — APPROVED** [review]

**Comment by rhysd** [comment]
Thanks for the review.

**Pull request merged**
