### PR TITLE
Fix insert text

### PR DESCRIPTION
**Pull request by mattn**
image

Vim always insert active candidate while selecting items in popup. So the inserted text might be wrong. Please see discussion about Metals and Vim's behavior.

https://twitter.com/olafurpg/status/1208442913266577409

I discussed how to fix this behavior with @hrsh7th . And we decided some rules for how to make insertion text.

* When insertTextFormat==2, it should prefer insertText. But it may include placeholder.
* When insertTextFormat!=2, use insertText since it is plain-text.
* When it have textEdit, the inserted text will be modified in later, so insert only word.
* Otherwize, insert label since it should be what the server want to insert.

### CODE REVIEW

**Comment by mattn** [comment]
I'll fix tests.

**Comment by prabirshrestha** [comment]
I use vsnip for snippets. Would it still continue to work? 

https://github.com/hrsh7th/vim-vsnip

**Comment by mattn** [comment]
Yes, I use vim-vsnip, too.

**Comment by hrsh7th** [comment]
Checked
- intelephense
- vim-language-server
- typescript-language-server`
- gopls
- clangd

**Pull request merged**
