### PR TITLE
Add support for virtual text diagnostics in Vim9

### PR DESCRIPTION
**Pull request by dotdash**

### CODE REVIEW

**Comment by prabirshrestha** [comment]
could you also add screenshots?

**Comment by dotdash** [comment]
ss2
ss1

**Comment by dotdash** [comment]
The `» ` prefix is from `let g:lsp_diagnostics_virtual_text_prefix = '» '`

**Comment by dotdash** [comment]
Ah, I see vim-lsp only delays the processing of incoming diagnostics, but then processes all of them, including outdated ones, and the textprop API then complains if a diagnostics refers to a line that no longer exists. I'll have to take a closer look at how things work, and decide whether the processing can be improved in general, or if I'll just have to drop diagnostics that refer to lines that no longer exist.

Thanks!

**Comment by prabirshrestha** [comment]
This is async problem, you can skip diagnostics that are in invalid line or column. We probably want `is_valid_range()` method that we can user everywhere for future async problems.  Having flags such as disabling diagnostics for current line or insert mode can also help.

**Comment by astronautindisguise** [comment]
Any progress on this?

**Comment by dotdash** [comment]
Should be good to go

**Comment by prabirshrestha** [comment]
Merged. Thanks. This looks great been using it and loving it!

**Pull request merged**
