### PR TITLE
Add explicit jump on the screen after LspDefinition.

### LINKED ISSUE #55: Jump to the top when retrieving defintion
Hi,

when I do ``Ctrl-]`` to get to the definition of the symbol under the cursor, it looks like the found definition is put just to the middle of the screen, so it looks I would press ``zz`` after the command. However, I would prefer if the found symbol was shown on the top of the screen. I have to literally run ``zt`` after every jump to the definition. Would it be possible to add some option switching vertical location of the jump target, please?

Thank you

### PR DESCRIPTION
**Pull request by mcepl**
Fixes #55.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
So been thinking about this for couple of days and don't think this solution would be the best. I would instead prefer this.

```vim
function! lsp#ui#vim#definition(opts) abort
endfunction
```

Where `opts` is a dictionary. Then we could have a command `:LspDefintion -vsplit 40% --left` or `:LspDefintion -tab`. Details on args need to be still flushed out here.

The user can create custom mappings for what ever args they want.

**Comment by mcepl** [comment]
I thinking about it, but I would probably like to avoid some gigantic ``if ... then ... else`` construct in the style of:
```python
if 'foo' in post_processing_arguments:
   do_something
elif 'bar' in post_processing_arguments:
   do_something_else
elif ...
```
What was your idea how to process that ``opt`` parameter?

**Comment by xtal8** [comment]
I would much more prefer default action to be nothing. Shifting screen with `zz` when target is already present on view would be distracting.

**Comment by mcepl** [comment]
@xtal8, @prabirshrestha like this?

**Comment by prabirshrestha** [comment]
What happens to `ctrl-o` does it come back or need to press twice to come back?

I'm hesitant to merge this since someone will some and request a feature to open in split or tabs and the current implement won't scale so it would be a breaking change.

**Comment by mcepl** [comment]
> What happens to ctrl-o does it come back or need to press twice to come back?

One ``Ctrl-O`` is enough.

> I'm hesitant to merge this since someone will some and request a feature to open in split or tabs and the current implement won't scale so it would be a breaking change.

I understand that, but I am afraid more complex requirements you will have (yes, new split came to my mind too) more horrible configuration you will need. We can end up with effectively one small DSL for just jumping. With that in my mind, I think that one-letter one configuration variable is rather good compromise.

**Comment by mcepl** [comment]
@prabirshrestha , I think I have responded to your question, haven't I?

**Comment by mcepl** [comment]
Hmm, I cannot reproduce even the original problem with the current ``master`` and vim 8.0.1520.

**Pull request closed without merging**
