### PR TITLE
use feedkeys(xxx, 'ni'), fix #1345

### LINKED ISSUE #1345: conflict with CompleteParameter.vim
to reproduce:

1. install some LSP, `pyls` for example, and prepare the min.vim

    ``` vim
    filetype plugin indent on
    syntax on
    set nocompatible
    let g:plug_home = $HOME . '/.vim/bundle'
    let g:plug_url_format = 'https://github.com/%s'
    execute 'source ' . g:plug_home . '/vim-plug/plug.vim'
    silent! call plug#begin()
    Plug 'junegunn/vim-plug'

    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/vim-lsp'
    Plug 'prabirshrestha/asyncomplete-lsp.vim'
    au User lsp_setup call lsp#register_server({
                        \   'name' : 'test',
                        \   'cmd' : [&shell, &shellcmdflag, 'pyls'],
                        \   'whitelist' : ['python'],
                        \ })

    Plug 'tenfyzhong/CompleteParameter.vim'
    Plug 'ZSaberLv0/CompleteParameter_generic.vim'
    function! ZF_Plugin_CompleteParameter_cr()
        if pumvisible()
            return "\<c-y>" . complete_parameter#pre_complete('')
        else
            return "\<c-g>u\<cr>"
        endif
    endfunction
    inoremap <silent><expr> <cr> ZF_Plugin_CompleteParameter_cr()

    call plug#end()
    ```

1. edit a python file:

    ```
    def test(a, b):
        return
    test|        // <= | is the cursor pos, and in insert mode
    ```

1. when typing `test`, the complete popup should open, use `<c-p>` to select and `<cr>` to trigger CompletePamameter
1. result:
image

### PR DESCRIPTION
**Pull request by ZSaberLv0**

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@ZSaberLv0 can you rebase to latest master and fix the merge conflicts?

**Comment by prabirshrestha** [comment]
ZSaberLv0

**Comment by ZSaberLv0** [comment]
> @ZSaberLv0 can you rebase to latest master and fix the merge conflicts?

@prabirshrestha merged

**Comment by prabirshrestha** [comment]
Have you also tried https://github.com/prabirshrestha/vim-lsp/pull/1429. Seems a bit similar

**Comment by ZSaberLv0** [comment]
> Have you also tried #1429. Seems a bit similar

it also solves the issue, by a different logic:
* use `feedkeys(xxx, 'ni')` : insert keys instead of append, process `s:on_complete_done_after` before other plugins
* use #1429 : wait until other plugin's done, and conditionally call `s:on_complete_done_after` by checking `mode()` state changes

**Comment by prabirshrestha** [comment]
Merged. Thanks!

**Comment by prabirshrestha** [comment]
Had to revert the PR. didn't work with https://github.com/cohama/lexima.vim.

**Pull request merged**
