### PR TITLE
use new floating window api for hover

### PR DESCRIPTION
**Pull request by prabirshrestha**
This uses the new floating window api for LspHover.

- [x] use the window floating window api for `:LspHover`
- [x] add support for preview window
- [x] use new `g:lsp_hover_ui` which can either be `'floating` or `preview` instead of `g:lsp_lsp_preview_float`.
- [x] add support `<plug>(lsp-hover-float)` and `<plug>(lsp-hover-preview)` besides `<plug>(lsp-hover)` 
- [x] add support for `:LspHover --ui=float` and `:LspHover --ui=preview`
- [x] add double tap support to focus into the floating window.
- [x] close on cursor moved
- [ ] verify scrolling for popupwindow
- [x] implement `s:compute_position()`
- [ ] implement preview support. (given that this is already broken we may want to fix this in different PR.
- [ ] add a plug mapping to convert floating window to preview so can focus and copy since double tap isn't supported in vim. (can be in different PR).
- [ ] set filetype to `markdown.lsp-hover`
- [ ] update docs

### CODE REVIEW

**Comment by prabirshrestha** [comment]
@hrsh7th could you help me in this PR. I mainly copied from how the documentation floating window api is used. So feel free to directly change and commit in the PR. I had added a todo checklist.

**Comment by hrsh7th** [comment]
I will look into it later.

**Comment by prabirshrestha** [comment]
@hrsh7th I tried to implement closing poup on move but sometime it works and sometime is just closes after a second the popup open. Not sure if it is due to markdown or something else causing the cursor to move.

**Comment by prabirshrestha** [comment]
@hrsh7th I also added `:LspHover --ui=preview` support. It is simple enough that I don't think we need to to put it in vital vs. Since almost everything is very specific to what we want. I do need to call `s:Makrdown.apply()` here.

**Comment by prabirshrestha** [comment]
@hrsh7th seems like i can now get a consistent repro where the `CursorMoved` gets called causing the hover window to close as soon as it opens. If you use `LspHover` on `printf` in vimscript you can see the floating window auto close after few milliseconds. wondering if this is due to the content size being too big and vim-vital-vs is doing some auto resize of the floating window or contents.

**Pull request merged**
