### PR TITLE
Fix various bugs when loading many buffers

### PR DESCRIPTION
**Pull request by analizator1**
I've hit a few bugs when trying to use vim-lsp and https://github.com/vim-ctrlspace/vim-ctrlspace. This happened when starting vim without any file (language server not started yet) and then loading a workspace with many buffers.
* languageId in a request was incorrectly set to "ctrlspace" because `filetype` option was not obtained by `getbufvar`. As a result `lsp_buffer_enabled` autocommand was not fired.
* An issue with an exception thrown in a folding request. The problem was invalid line count (greater than actual count) of a buffer. As a result LSP was not enabled for the buffer.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
can you have a look at tests. seems like it is failing.

**Comment by analizator1** [comment]
Strange - even if I open a job that succeeded and then "View raw logs" I can find a `Segmentation fault`, and most likely just a subset of tests were executed. Here: https://github.com/prabirshrestha/vim-lsp/actions/runs/6871148469/job/18688368071?pr=1511.

**Comment by analizator1** [comment]
After the last commit (a789e7173ae20ea851992cb8cc137f23be516193) tests pass, but the problem with 2 instances of clangd is occurring again. How to reproduce:
* load a workspace in vim-ctrlspace that contains only .cpp and .h files => there is one clangd instance
* now open a .c file => another clangd instance is started

`:CheckHealth` shows that everything should be fine:
```
lsp: health#lsp#check
========================================================================
## server status
  - OK: clangd: running

## server configuration: clangd
  - INFO:
    ### allowlist
    ['c', 'cpp', 'objc', 'objcpp', 'cuda']

## Performance
  - WARNING: Missing requirements to enable lua for faster performance.
```
I'm also using `mattn/vim-lsp-settings` plugin so maybe there is an issue with it.

**Comment by analizator1** [comment]
I've found a proper workaround to this issue:
* Language server (this was clangd) was started twice. It was caused by a missing `return`.

that is to avoid using `mattn/vim-lsp-settings` and instead to register clangd server by `lsp#register_server`. I have reverted my changes to this function.

**Comment by analizator1** [comment]
Could you approve awaiting PR tests? Thanks

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
