### PR TITLE
Format Hover Pop-up Window

### PR DESCRIPTION
**Pull request by numEricL**
Addresses issue #1249 where wrapped lines overflow in the pop-up window. Additionally fixes an issue that prevented scrolling to the last two lines of a popup window.

1) Applies Vim's `gq` command to each individual line of content returned by language server. User configurable through `formatprg` builtin.

2) Allows scrolling to the last lines of a popup window. An offset did not take into consideration the window's border size.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
can you fix the lint issue?

**Comment by prabirshrestha** [comment]
You will need to add abort in the function

**Comment by numEricL** [comment]
I think I have it this time, I didn't see any checks from a linter.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

**Pull request merged**
