### PR TITLE
Add :LspStopServer

### PR DESCRIPTION
**Pull request by tyru**
This also fixes missing `|LspStatus|` in ToC.

### CODE REVIEW

**Comment by prabirshrestha** [comment]
Can you fix merge conflicts?

**Comment by tyru** [comment]
oops, fixing now.

**Comment by tyru** [comment]
@prabirshrestha fixed.

But I found the problem that `:LspStatus` shows `exited` for stopped server...
`gopls` process seems to be running, though.

I'll upload gif file... (converting now)

**Comment by tyru** [comment]
CI failed... but it seems master branch has been broken now.

**Comment by prabirshrestha** [comment]
Merged. Thanks.

CI has been pain breaking all the time. I really need to work on setting up docker for reproducible builds.

**Pull request merged**
